### ISSUE TITLE
bbPress and BuddyPress Compatibility

### ISSUE THREAD

**Issue by lucaskeiser** [DrewAPicture/remove-dashboard-access#3]
This plugin is not compatible with bbPress and BuddyPress in it's current format.

`Notice: bbp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). Please see Debugging in WordPress for more information. (This message was added in version 2.3.) in/wp-includes/functions.php on line 3547 Notice: bp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). Please see Debugging in WordPress for more information. (This message was added in version 1.7.) in /wp-includes/functions.php on line 3547`

This is easy enough to fix. In remove-dashboard-access.php wrap everything after line 15 in a function and then add `add_action( 'init', 'your_function');` and everything should work fine.

**Comment by lucaskeiser** [comment]
It might also need to be added for `admin_init` but I'm not positive.

**Comment by DrewAPicture** [comment]
Hi, thanks for the issue. However, this has already been reported in #2.
