### ISSUE TITLE
Make the whitelisted page(s) list and/or redirect URL filterable

### ISSUE THREAD

**Issue by ncd76** [DrewAPicture/Remove-Dashboard-Access#4]
I'm using a modal login system. Could the redirect page give an option to stay / reload the same page the user is currently on?

Thx

**Comment by DrewAPicture** [comment]
The next version will have a filter on the whitelisted pages to skip redirecting.

**Comment by ncd76** [comment]
Sounds perfect, could that have a wildcard system to eliminate the whole site or folders at once?

**Comment by DrewAPicture** [comment]
No, that would be up to you to handle in your filter callback.
